@aooai_endpoint={{$dotenv AZURE_OPENAI_ENDPOINT}}
@aoai_key={{$dotenv AZURE_OPENAI_KEY}}
@aoai_deployment={{$dotenv AZURE_OPENAI_DEPLOYMENT}}

POST {{aooai_endpoint}}openai/deployments/{{aoai_deployment}}/completions?api-version=2023-05-15
Content-Type: application/json
api-key: {{aoai_key}}

{
  "model": "gpt-5-turbo-1",
  "prompt": "Once upon a time",
  "max_tokens": 10
}



###

POST http://localhost:8000/openai/deployments/{{aoai_deployment}}/completions?api-version=2023-05-15
Content-Type: application/json
api-key: {{aoai_key}}

{
  "model": "gpt-5-turbo-1",
  "prompt": "Once upon a time",
  "max_tokens": 10
}




###

POST {{aooai_endpoint}}openai/deployments/{{aoai_deployment}}/chat/completions?api-version=2023-12-01-preview
Content-Type: application/json
api-key: {{aoai_key}}

{
  "messages": [{
    "role": "user",
    "content": "What is the meaning of life?"
    }],
  "model": "gpt-5-turbo-1"
}

###

POST {{aooai_endpoint}}openai/deployments/{{aoai_deployment}}/chat/completions?api-version=2023-12-01-preview
Content-Type: application/json
api-key: {{aoai_key}}

{
  "messages": [
    {"role": "user", "content": "What is the furthest human-made object from Earth?"},
    {"role": "assistant", "content": "As an AI language model, I don't have the latest information on this. However, as of August 2021, the furthest human-made object from Earth is the Voyager 1 spacecraft. It was launched in 1977 and is currently over 14 billion miles away from Earth and is still transmitting data."},

    {"role": "user", "content": "How fast is it travelling?"},
    {"role": "assistant", "content": "As of August 2021, Voyager 1 is traveling at a speed of about 17.7 km/s (62,136 km/h or 38,614 miles per hour). This is about 0.006% of the speed of light, which means it would take over 17,000 years to travel one light-year."},

    {"role": "user", "content": "How much does it weigh?"},
    {"role": "assistant", "content": "The total weight of the Voyager 1 spacecraft at launch was approximately 773 kilograms (1,704 pounds), including the scientific instruments, electronics, and propulsion system. However, as it has been traveling through space for more than four decades, some of its expended fuel and other parts have been jettisoned, so its actual weight is a bit less than the launch weight."}
  ],
  "model": "gpt-5-turbo-1"
}
###

POST http://localhost:8000/openai/deployments/{{aoai_deployment}}/chat/completions?api-version=2023-12-01-preview
Content-Type: application/json
api-key: {{aoai_key}}

{
  "messages": [
    {"role": "user", "content": "What is the furthest human-made object from Earth?"},
    {"role": "assistant", "content": "As an AI language model, I don't have the latest information on this. However, as of August 2021, the furthest human-made object from Earth is the Voyager 1 spacecraft. It was launched in 1977 and is currently over 14 billion miles away from Earth and is still transmitting data."},

    {"role": "user", "content": "How fast is it travelling?"},
    {"role": "assistant", "content": "As of August 2021, Voyager 1 is traveling at a speed of about 17.7 km/s (62,136 km/h or 38,614 miles per hour). This is about 0.006% of the speed of light, which means it would take over 17,000 years to travel one light-year."},

    {"role": "user", "content": "How much does it weigh?"},
    {"role": "assistant", "content": "The total weight of the Voyager 1 spacecraft at launch was approximately 773 kilograms (1,704 pounds), including the scientific instruments, electronics, and propulsion system. However, as it has been traveling through space for more than four decades, some of its expended fuel and other parts have been jettisoned, so its actual weight is a bit less than the launch weight."}
  ],
  "model": "gpt-5-turbo-1"
}
