SIMULATOR_KEY_OPERATION_NAME = "Operation-Name"
SIMULATOR_KEY_DEPLOYMENT_NAME = "Deployment-Name"
SIMULATOR_KEY_LIMITER = "Limiter"
SIMULATOR_KEY_OPENAI_COMPLETION_TOKENS = "XOpenAI-Tokens-Completion"
SIMULATOR_KEY_OPENAI_TOTAL_TOKENS = "XOpenAI-Tokens-Total"

RECORDED_DURATION_MS = "Simulator-Recorded-Duration"
